site_name: U.R.Lucky

nav:
  - index.md

theme:
  name: material
  language: en # (1)!
  analytics:
    gtag: G-36HTPNNRCG

extra:
  alternate:
    - name: English
      link: /en/ # (1)!
      lang: en
    - name: 中文
      link: /zh/
      lang: zh

plugins:
  - privacy
